<a href="https://colab.research.google.com/github/treyra/CS155_miniproject/blob/data_visualization_v1/Data_Imputation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notebook for data imputation - in progress



Import statements

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [35]:
df = pd.read_csv('https://raw.githubusercontent.com/treyra/CS155_miniproject/master/WILDFIRES_TRAIN.csv',sep=',', header=0)
df.head()

id   LATITUDE   LONGITUDE  ...   SOURCE_REPORTING_UNIT_NAME        DATE  LABEL
0   0  38.205000 -120.335000  ...   Stanislaus National Forest  1992-01-01      1
1   1  33.813100  -85.104300  ...  Georgia Forestry Commission  1992-01-01      4
2   2  32.201000  -82.498700  ...  Georgia Forestry Commission  1992-01-01      2
3   3  32.509300  -81.708600  ...  Georgia Forestry Commission  1992-01-01      4
4   4  33.663889 -116.171944  ...         CDF - Riverside Unit  1992-01-01      2

[5 rows x 11 columns]

In [36]:
# convert State from strings to numbers
df['STATE'] = df['STATE'].replace(['CA'],1)
df['STATE'] = df['STATE'].replace(['GA'],2)
df.head()

id   LATITUDE   LONGITUDE  ...   SOURCE_REPORTING_UNIT_NAME        DATE  LABEL
0   0  38.205000 -120.335000  ...   Stanislaus National Forest  1992-01-01      1
1   1  33.813100  -85.104300  ...  Georgia Forestry Commission  1992-01-01      4
2   2  32.201000  -82.498700  ...  Georgia Forestry Commission  1992-01-01      2
3   3  32.509300  -81.708600  ...  Georgia Forestry Commission  1992-01-01      4
4   4  33.663889 -116.171944  ...         CDF - Riverside Unit  1992-01-01      2

[5 rows x 11 columns]

In [ ]:
df.STATE.unique()

array(['1', '2'], dtype=object)

In [ ]:
len(df.FIPS_NAME.unique())

216

In [33]:
df.FIPS_CODE.unique()
#len(df.FIPS_CODE.unique())

array([ nan, 143., 209.,  31.,  71., 129., 309., 279.,  93., 271.,  69.,
       175., 115., 183., 235., 233.,  27., 127., 205., 319.,  49., 315.,
       131., 185., 153.,   3., 269., 201.,  87., 317., 287., 181.,  17.,
         1.,  39.,  75., 109., 117., 273., 111., 165., 139., 255., 199.,
       251.,   5.,  91.,  95., 231., 151., 177., 253., 299., 179., 321.,
       225.,  29.,  81., 293.,  47., 103.,  45., 275., 283.,  25., 195.,
        33., 155., 107., 277., 211., 229., 305., 257., 223., 217., 121.,
        57., 101., 133.,  99., 161., 171., 301., 135., 237., 141.,  43.,
       249.,  97., 193., 113.,  73., 173.,  19., 227.,  77., 303.,  13.,
        15.,  61., 261., 289., 167., 221., 105.,  79., 119., 169., 247.,
       297.,  11., 159., 191.,  55., 267., 157., 295., 219.,  59., 213.,
       137., 281., 311., 313.,  83.,  21., 187., 197., 291., 307.,  51.,
       243.,  23., 189., 259., 207.,   9., 245.,  30., 263.,  63.,   7.,
       149., 147., 285., 123., 145., 163.,  89., 26

In [37]:
# transform FIPS_NAME in integer
for i,fipsname in enumerate(df.FIPS_NAME.unique()):
  df['FIPS_NAME'] = df['FIPS_NAME'].replace([str(fipsname)],[i])

In [38]:
# transform SOURCE_REPORTING_UNIT_NAME in integer
for i,unitname in enumerate(df.SOURCE_REPORTING_UNIT_NAME.unique()):
  df['SOURCE_REPORTING_UNIT_NAME'] = df['SOURCE_REPORTING_UNIT_NAME'].replace([str(unitname)],[i])

In [39]:
df.head()

id   LATITUDE   LONGITUDE  ...  SOURCE_REPORTING_UNIT_NAME        DATE  LABEL
0   0  38.205000 -120.335000  ...                           0  1992-01-01      1
1   1  33.813100  -85.104300  ...                           1  1992-01-01      4
2   2  32.201000  -82.498700  ...                           1  1992-01-01      2
3   3  32.509300  -81.708600  ...                           1  1992-01-01      4
4   4  33.663889 -116.171944  ...                           2  1992-01-01      2

[5 rows x 11 columns]

In [ ]:
# set all missing values to np.nan for simple imputer to work (just to make sure)
df.fillna(np.nan)

id   LATITUDE  ...        DATE LABEL
0            0  38.205000  ...  1992-01-01     1
1            1  33.813100  ...  1992-01-01     4
2            2  32.201000  ...  1992-01-01     2
3            3  32.509300  ...  1992-01-01     4
4            4  33.663889  ...  1992-01-01     2
...        ...        ...  ...         ...   ...
285377  285377  32.359105  ...  2009-12-30     4
285378  285378  38.346342  ...  2009-12-30     2
285379  285379  32.780596  ...  2009-12-30     2
285380  285380  33.985000  ...  2009-12-30     2
285381  285381  33.470031  ...  2009-12-31     2

[285382 rows x 11 columns]

In [ ]:
# replacing missing values with most frequent
# probably not the best idea, should instead learn the fips name and code from lat+lon
# no idea about discovery time
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values= np.nan, strategy='most_frequent')
imp.fit(df)
imp.transform(df)
T=imp.transform(df)
# make pandas frame again from imputed data
df2 = pd.DataFrame({'id': T[:, 0], 'LATITUDE': T[:, 1], 'LONGITUDE': T[:, 2], 'STATE': T[:, 3], 'DISCOVERY_TIME': T[:, 4], 'FIRE_SIZE': T[:, 5], 'FIPS_NAME': T[:, 6], 'FIPS_CODE': T[:, 7], 'SOURCE_REPORTING_UNIT_NAME': T[:, 8], 'DATE': T[:, 9], 'LABEL': T[:, 10]})
df2.head()

id LATITUDE LONGITUDE  ... SOURCE_REPORTING_UNIT_NAME        DATE LABEL
0  0   38.205  -120.335  ...                          0  1992-01-01     1
1  1  33.8131  -85.1043  ...                          1  1992-01-01     4
2  2   32.201  -82.4987  ...                          1  1992-01-01     2
3  3  32.5093  -81.7086  ...                          1  1992-01-01     4
4  4  33.6639  -116.172  ...                          2  1992-01-01     2

[5 rows x 11 columns]

In [29]:
# find out exactly how many values are missing and in which columns to get a feel for the time needed to impute
# impute fips code from closest lat lon neighbor
# prepare dataframe - Latitude + Longitude data is complete
print(df['LATITUDE'].isnull().values.any()) # checked of longitude also
df_impute_code = df.drop(['id','STATE','DISCOVERY_TIME','FIRE_SIZE','FIPS_NAME','SOURCE_REPORTING_UNIT_NAME','DATE','LABEL'], axis=1)
df_impute_code.head()
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=1)
df_code_imputed = imputer.fit_transform(df_impute_code)

In [41]:
# make pandas frame again from imputed data
df_imputed_1 = pd.DataFrame({'LATITUDE': df_code_imputed[:, 0], 'LONGITUDE': df_code_imputed[:, 1], 'FIPS_CODE': df_code_imputed[:, 2],})
df_imputed_1.head()

LATITUDE   LONGITUDE  FIPS_CODE
0  38.205000 -120.335000        9.0
1  33.813100  -85.104300      143.0
2  32.201000  -82.498700      209.0
3  32.509300  -81.708600       31.0
4  33.663889 -116.171944       65.0

In [48]:
# then impute fips name from fips code + lat + lon neighbor
df_to_impute_2 = pd.DataFrame({'LATITUDE': df_code_imputed[:, 0], 'LONGITUDE': df_code_imputed[:, 1], 'FIPS_CODE': df_code_imputed[:, 2]})
# add fips name to df
df_to_impute_2['FIPS_NAME']=df['FIPS_NAME']
imputer = KNNImputer(n_neighbors=1)
df_code_imputed_2 = imputer.fit_transform(df_to_impute_2)

AttributeError: ignored

In [49]:
# make pandas frame again from imputed data
df_code_imputed_2 = pd.DataFrame({'LATITUDE': df_code_imputed_2[:, 0], 'LONGITUDE': df_code_imputed_2[:, 1], 'FIPS_CODE': df_code_imputed_2[:, 2],'FIPS_NAME': df_code_imputed_2[:, 3]})
df_code_imputed_2.head()

LATITUDE   LONGITUDE  FIPS_CODE  FIPS_NAME
0  38.205000 -120.335000        9.0      192.0
1  33.813100  -85.104300      143.0        1.0
2  32.201000  -82.498700      209.0        2.0
3  32.509300  -81.708600       31.0        3.0
4  33.663889 -116.171944       65.0      168.0

In [50]:
# put it together in a dataframe back in order again
# change the changed columns of df_original
df_imputed = df
# add the imputed values for name and code
df_imputed['FIPS_NAME']=df_code_imputed_2['FIPS_NAME']
df_imputed['FIPS_CODE']=df_code_imputed_2['FIPS_CODE']
# what to do about date and discovery time - TBD??
df_imputed.head()

id   LATITUDE   LONGITUDE  ...  SOURCE_REPORTING_UNIT_NAME        DATE  LABEL
0   0  38.205000 -120.335000  ...                           0  1992-01-01      1
1   1  33.813100  -85.104300  ...                           1  1992-01-01      4
2   2  32.201000  -82.498700  ...                           1  1992-01-01      2
3   3  32.509300  -81.708600  ...                           1  1992-01-01      4
4   4  33.663889 -116.171944  ...                           2  1992-01-01      2

[5 rows x 11 columns]

In [57]:
# put it together in a dataframe and save
from google.colab import  drive

def save_csv(df, savestr):
  drive.mount("/drive", force_remount=True)
  df.to_csv('/drive/My Drive/CS155_miniproject_1/'+str(savestr)+'.csv')

In [58]:
save_csv(df_imputed,'traindata_fipsname_code_imputed')

Mounted at /drive


In [90]:
# then impute discovery time from ??? year + season + label ???
# convert date column into 2 columns - year and day of the year
import datetime 
dates = pd.DataFrame({'DATE':df['DATE']})
df.dtypes
dates['DATE'] = pd.to_datetime(dates['DATE'])
year = np.zeros(len(dates['DATE']))
day = np.zeros(len(dates['DATE']))
for i in range(0,len(dates['DATE'])):
  timetuple = dates['DATE'][:][i].timetuple()
  year[i] = timetuple.tm_year
  day[i] = timetuple.tm_yday
print(year)
print(day)

[1992. 1992. 1992. ... 2009. 2009. 2009.]
[  1.   1.   1. ... 364. 364. 365.]


In [96]:
# add to dataframe
df.insert(9,'YEAR',year)
df.insert(10,'DAY',day)
df = df.drop(['DATE'],axis=1)
df.head()

id   LATITUDE   LONGITUDE  ...    YEAR  DAY  LABEL
0   0  38.205000 -120.335000  ...  1992.0  1.0      1
1   1  33.813100  -85.104300  ...  1992.0  1.0      4
2   2  32.201000  -82.498700  ...  1992.0  1.0      2
3   3  32.509300  -81.708600  ...  1992.0  1.0      4
4   4  33.663889 -116.171944  ...  1992.0  1.0      2

[5 rows x 12 columns]

In [97]:
save_csv(df_imputed,'traindata_fipsname_code_imputed_year_day')

Mounted at /drive


In [ ]:
# normalize data tbd how
# impute discovery time from ?? - year/day/state/fips_code?

In [59]:
# ALL IN ONE - TOO SLOW !!! and probs not too useful
# df.dtypes
# df['DATE'] = pd.to_datetime(df['DATE'])
# # took out date data, if we want to keep it for imputation need to convert to numeric, but doesnt really have to do with zip?/ but maybe with detection time
# df3 = df.drop(['DATE'], axis=1)
# # maybe use K-Nearest Neighbor to impute data
# from sklearn.impute import KNNImputer
# imputer = KNNImputer(n_neighbors=2)
# imputer.fit_transform(df3)
# df3.head()
